import os

YOUTH_API_BASE_URL = os.getenv("YOUTH_API_BASE_URL", "https://www.youthcenter.go.kr")
YOUTH_API_KEY = _secret("YOUTH_API_KEY", "")
YOUTH_POLICY_LIST_PATH = os.getenv("YOUTH_POLICY_LIST_PATH", "/opi/youthPlcyList.do")
YOUTH_SPACE_LIST_PATH = os.getenv("YOUTH_SPACE_LIST_PATH", "/opi/youthSpaceList.do")
YOUTH_CONTENT_LIST_PATH = os.getenv("YOUTH_CONTENT_LIST_PATH", "/opi/youthContentList.do")
YOUTH_POLICY_DETAIL_PATH = os.getenv("YOUTH_POLICY_DETAIL_PATH", "/opi/youthPlcyDtl.do")
YOUTH_SPACE_DETAIL_PATH = os.getenv("YOUTH_SPACE_DETAIL_PATH", "/opi/youthSpaceDtl.do")
YOUTH_CONTENT_DETAIL_PATH = os.getenv("YOUTH_CONTENT_DETAIL_PATH", "/opi/youthContentDtl.do")
CACHE_DB_PATH = os.getenv("YOUTH_CACHE_DB_PATH", "youth_cache.db")
CACHE_TTL_SECONDS = int(os.getenv("YOUTH_CACHE_TTL_SECONDS", str(30 * 60)))
DETAIL_TTL_SECONDS = int(os.getenv("YOUTH_DETAIL_TTL_SECONDS", "120"))
HTTP_TIMEOUT_SECONDS = float(os.getenv("YOUTH_API_TIMEOUT_SECONDS", "8"))
HTTP_MAX_RETRIES = int(os.getenv("YOUTH_API_MAX_RETRIES", "3"))
HTTP_BACKOFF_SECONDS = float(os.getenv("YOUTH_API_BACKOFF_SECONDS", "0.7"))
HTTP_RATE_LIMIT_PER_MINUTE = int(os.getenv("YOUTH_API_RATE_LIMIT_PER_MINUTE", "120"))
