[theme]
primaryColor        = "#667eea"
backgroundColor     = "#000000"
secondaryBackgroundColor = "#000000"
textColor           = "#ffffff"
font                = "sans serif"

[browser]
gatherUsageStats = false
